name: Generate Snake Animation

on:
  schedule:
    # Jalan otomatis tiap hari jam 00:00 UTC (~07:00 WIB) agar animasi selalu update
    - cron: "0 0 * * *"
  workflow_dispatch: {}   # supaya bisa dijalankan manual dari tab Actions
  push:
    branches:
      - main               # jalan otomatis tiap kamu push ke branch utama

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake animation
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: etty7
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push output to "output" branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
